apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: wssource
  namespace: knative-eventing-websocket-source
spec:
  template:
    spec:
      containers:
        - image: docker.io/josiemundi/wssourcecloudevents
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display