# Service that exposes wseventsource app.
# This will be the subscriber for the Trigger
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: knative-eventing-websocket-source
  # labels:
  #  serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        # - image: docker.io/josiemundi/blockchaincloudevents
        - image: docker.io/josiemundi/webserver-matt
          ports:
          # - name: h2c
          #   containerPort: 9080
          - name: http1
            containerPort: 8080